[tool]
enable = true
name = "system"
exec = "target/release/system"

[server]
port = 7879

[[examples]]
query = "turn off pc after 30 minutes"
action = "wait"
data = { mins = 30 }
next = "turn off pc"

# Wait some time before next task
[actions.wait]
enable = true
description = "Waits some time."
examples = [
  [
    "... after 1.5 hours 15 seconds",
    { hours = 1, mins = 30, secs = 15 },
  ],
]
[actions.wait.arguments]
hours = { format = "integer", optional = true }
mins = { format = "integer", optional = true }
secs = { format = "integer", optional = true }
millis = { format = "integer", optional = true }

# System power operations
[actions.power]
enable = true
description = "Power operations: turnoff, sleep, reboot, lock."
examples = [["turn off pc", { mode = "turnoff" }]]
[actions.power.arguments]
mode = { format = "string", variants = [
  "turnoff",
  "sleep",
  "reboot",
  "lock",
], optional = false }

# TODO: Launch/Kill applications 
[actions.app]
enable = false
description = ""
examples = [["", {}]]
[actions.app.arguments]

# Search+Play local music
[actions.music]
enable = true
description = "Search/Play local music. With search=true - returns matches without play."
examples = [
  [
    "play any rock",
    { genre = "rock" },
  ],
  [
    "play Disturbed",
    { artist = "Disturbed" },
  ],
  [
    "play Disturbed - The Sickness",
    { artist = "Disturbed", album = "The Sickness" },
  ],
  [
    "search rock compositions",
    { genre = "rock", search = true },
  ],
]
[actions.music.arguments]
genre = { format = "string", optional = true }
artist = { format = "string", optional = true }
album = { format = "string", optional = true }
song = { format = "string", optional = true }
search = { format = "boolean", optional = true }

# Set system audio-volume
[actions.volume]
enable = true
description = "Set audio volume (or change by delta). Value 1.0 = 100% of volume."
examples = [
  [
    "decrease volume by 20%",
    { delta = -0.2 },
  ],
  [
    "set volume to 50%",
    { volume = 0.5 },
  ],
]
[actions.volume.arguments]
delta = { format = "float", optional = true }
volume = { format = "float", optional = true }
