[tool]
enable = true
name = "pc"
path = "target/release/pc.exe"

[actions.power]
description = "Turns off computer or puts to sleep with timeout in seconds (if you need minutes or hours - calculate. for example, 30 minutes = 1800 sec). Mode 'lock' - do lock pc session. Mode 'cancel' do cancel power operation."
[actions.power.arguments]
mode = { format = "string", variants = ["off", "sleep", "reboot", "lock", "cancel"], optional = false }
timeout = { format = "integer", optional = true }

[actions.play]
description = "Opens playlist folder, where: author - is music author or playlist name, album - subfolder in founded music"
[actions.play.arguments]
author = { format = "string", optional = false }
album = { format = "string", optional = true }
