[tool]
enable = true
name = "pc"
exec = "target/release/pc-control"

[server]
port = 7879

[actions.power]
descr = "Turns off computer or sleep it with timeout in seconds (if you need minutes or hours - calculate. for example, 30 minutes = 1800 sec). Mode 'cancel' do cancel power operation."
[actions.power.args]
mode = { format = "string", variants = [
  "turnoff",
  "sleep",
  "reboot",
  "lock",
  "cancel",
], optional = false, example = "turnoff" }
timeout = { format = "integer", optional = true, example = "5" }

[actions.play]
descr = "Opens playlist, where: author - is author or playlist name, album - subfolder in founded music"
[actions.play.args]
author = { format = "string", optional = false, example = "Geoxor" }
album = { format = "string", optional = true, example = "Stardust" }

[actions.volume]
descr = "Change audio volume by delta [0..100]. Warning: If need to set one concrete volume (not delta change) - set force=true (default: false)."
[actions.volume.args]
delta = { format = "integer", optional = false, example = "-20" }
force = { format = "boolean", optional = true, example = "false" }
